sudo: required

language: bash

services:
    - docker

before_install:
    - docker info
    - docker version

install:
    - docker build -t oleggorj/jenkins

script:
    - docker image ls | grep jenkins

after_script:
    - docker ps -a
